#!/bin/bash
echo
echo "///////////////////////"
echo
echo "Executing BatchAudioMixer..."
echo
echo "(cd to this directory if executing from the terminal)"
echo
echo "///////////////////////"
echo
python3 BatchAudioMixer.py